name: ciecplib
channels:
  - conda-forge
dependencies:
  - python>=3
  # build
  - pip
  - setuptools
  # install
  - m2crypto
  - pyopenssl
  - requests
  - requests-ecp
  # docs
  - sphinx
  - sphinx-argparse
  - sphinx-automodapi
  - sphinx_rtd_theme
  - sphinx-tabs
